version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date` 
      - echo "Enriching index.php as part of build stage" >> index.php
   
artifacts:
  type: 
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
